{% set name = "libertem" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libertem-{{ version }}.tar.gz
  sha256: 698ace6b5a9c3e1fa9bab559fa786394d0338ea38d28d71a1f1b8a42c81a1c1f

build:
  skip: true  # [py<37]
  entry_points:
    - libertem-server=libertem.web.cli:main
    - libertem-worker=libertem.executor.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - sparse
    - distributed >=2.19.0, !=2023.6.1
    - click
    - tornado >=5
    - matplotlib-base
    - pillow
    - h5py
    - psutil
    - numba >=0.51
    - ncempy >=1.4
    - pywin32-on-windows !=226  # [win]
    - scikit-image
    - cloudpickle
    - jsonschema
    - scikit-learn <1.3.0
    - tqdm
    - threadpoolctl >=3.0
    - nbformat
    - nbconvert
    - autopep8
    - pycodestyle <2.11
    - empyre >=0.3.0
    - defusedxml
    - typing-extensions
    - opentelemetry-api
    - tblib
    - tomli
    - sparseconverter >=0.3.3
    - numexpr !=2.8.6

test:
  imports:
    - libertem
  commands:
    - pip check
    - libertem-server --help
    - libertem-worker --help
    - pytest tests
  source_files:
    - tests
    - conftest.py
    - pytest.ini
  requires:
    - pip
    - pytest >=6
    - pytest-cov
    - pytest-asyncio >0.11
    - pytest-xdist
    - pytest-env
    - pytest-benchmark
    - aiohttp
    - websockets
    - ipykernel
    - joblib

about:
  home: https://libertem.github.io/LiberTEM/
  summary: Open pixelated STEM framework
  license: GPL-3.0-or-later AND MIT
  license_file:
    - LICENSE
    - src/libertem/common/LICENSE
    - src/libertem/io/LICENSE
  description: |
    LiberTEM is an open source platform for high-throughput distributed
    processing of large-scale binary data sets and live data streams
    using a modified MapReduce programming model. The current focus is
    pixelated scanning transmission electron microscopy (STEM)
    and scanning electron beam diffraction data.
  doc_url: https://libertem.github.io/LiberTEM/
  dev_url: https://github.com/LiberTEM/LiberTEM

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
