{% set name = "libertem" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libertem-{{ version }}.tar.gz
  sha256: fd3be06af768668b83eae37dd1b55ce3f122f8d24cdaa70ff61d8cf396f236f3

build:
  skip: true  # [py<39]
  entry_points:
    - libertem-server=libertem.web.cli:main
    - libertem-worker=libertem.executor.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python
    - numpy
    - scipy >=1.4.1
    - sparse
    - distributed >=2.19.0,!=2023.6.1
    - click
    - tornado >=5
    - matplotlib-base
    - pillow
    - h5py
    - psutil
    - numba >=0.53  # [py<310]
    - numba >=0.55  # [py==311]
    - numba >=0.57  # [py==312]
    - numba >=0.59  # [py==313]
    - numba >=0.61  # [py==314]
    - numba >=0.61  # [py>=314]
    - ncempy >=1.10
    - pywin32-on-windows !=226  # [win]
    - scikit-image
    - cloudpickle
    - jsonschema
    - scikit-learn
    - tqdm
    - threadpoolctl >=3.0
    - nbformat
    - nbconvert
    - autopep8
    - defusedxml
    - typing-extensions
    - opentelemetry-api
    - tblib
    - tomli
    - sparseconverter >=0.4.0
    - numexpr !=2.8.6
    - ipympl
    - jupyter-ui-poll
    - colorcet

test:
  imports:
    - libertem
  commands:
    - pip check
    - libertem-server --help
    - libertem-worker --help
    - pytest -k "not test_pipelined" --deselect=tests/io/test_tiling_negotiation.py::test_multi_by_frame_wins --deselect=tests/test_context.py::test_dynamic_parameter_update_integration tests
  source_files:
    - tests
    - conftest.py
    - pytest.ini
  requires:
    - pip
    - pytest >=6
    - pytest-cov
    - pytest-asyncio >0.11,!=0.22.0,<0.23.0
    - pytest-xdist
    - pytest-env
    - pytest-benchmark
    - aiohttp
    - nest-asyncio
    - websockets <14
    - ipykernel
    - joblib
    - setuptools

about:
  home: https://libertem.github.io/LiberTEM/
  summary: Open pixelated STEM framework
  license: MIT
  license_file:
    - LICENSE
  description: |
    LiberTEM is an open source platform for high-throughput distributed
    processing of large-scale binary data sets and live data streams
    using a modified MapReduce programming model. The current focus is
    pixelated scanning transmission electron microscopy (STEM)
    and scanning electron beam diffraction data.
  doc_url: https://libertem.github.io/LiberTEM/
  dev_url: https://github.com/LiberTEM/LiberTEM

extra:
  recipe-maintainers:
    - sk1p
    - uellue
    - matbryan52
